site_name: Projeto Base
repo_url: https://github.com/vladimirmaciel/projeto-base
repo_name: vladimirmaciel/projeto-base
edit_uri: tree/master/docs
theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.share
markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css
